((java-mode . ((indent-tabs-mode . nil)
               (tab-width . 4)
               (display-fill-column-indicator-column . 110)))
 (kotlin-mode . ((indent-tabs-mode . nil)
                 (tab-width . 4)
                 (display-fill-column-indicator-column . 120)))
 (kotlin-ts-mode . ((indent-tabs-mode . nil)
                    (tab-width . 4)
                    (display-fill-column-indicator-column . 120)))
 (groovy-mode . ((indent-tabs-mode . nil)
                 (tab-width . 4)))
 (jenkinsfile-mode . ((indent-tabs-mode . nil)
                      (tab-width . 4)
                      (display-fill-column-indicator-column . 100))))
